Simplify scripts

diff --git a/cookiefire b/cookiefire
--- a/cookiefire
+++ b/cookiefire
@@ -1,55 +1,34 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # -*- mode:sh -*-
 
+profile=${1:-default}
+
 die() {
-    echo >&2 "$*"
-    exit 1
+  echo >&2 "$*"
+  exit 1
 }
-
-
 
 cleanup() {
-    rm -f "$tmpfile"
+  rm -f "$tmpfile"
 }
-trap cleanup  EXIT INT QUIT TERM
+trap cleanup EXIT INT QUIT TERM
 
-# Run older ld (pseudo condition)
-
-if [ "$#" == "0" ];  then
-    profile=default
-elif [ "$#" == "1"  ]; then
-    profile=$1
-else
-    die "usage $0 [profile]"
-fi;
-
+if [ "$#" -gt 1 ]; then
+  die "usage: $0 [profile]"
+fi
 
 extract_cookies() {
+  local sqlfile="$1"
 
-if [ "$#" -ge 1 ]; then
-    sqlfile="$1"
-else
-    if tty -s; then
-    sqlfile=$(ls -t ~/.mozilla/firefox/*/cookies.sqlite | head -1)
+  if [ ! -r "$sqlfile" ]; then
+    die "Error. File $sqlfile is not readable."
+  fi
 
-    sqlfile="-"     # Will use 'cat' below to read stdin
-    fi
-fi
+  # Copy cookies.sqlite to avoid lock issues
+  cp "$sqlfile" "$tmpfile"
 
-if [ "$sqlfile" != "-" -a ! -r "$sqlfile" ]; then
-    echo "Error. File $sqlfile is not readable." >&2
-    exit 1
-fi
-
-# We have to copy cookies.sqlite, because FireFox has a lock on it
-cat "$sqlfile" >> $tmpfile
-
-
-# This is the format of the sqlite database:
-# CREATE TABLE moz_cookies (id INTEGER PRIMARY KEY, name TEXT, value TEXT, host TEXT, path TEXT,expiry INTEGER, lastAccessed INTEGER, isSecure INTEGER, isHttpOnly INTEGER);
-
-echo "# Netscape HTTP Cookie File"
-sqlite3 -separator $'\t' $tmpfile <<- EOF
+  echo "# Netscape HTTP Cookie File"
+  sqlite3 -separator $'\t' "$tmpfile" <<-EOF
 .mode tabs
 .header off
 select host,
@@ -62,14 +41,13 @@ value
 from moz_cookies;
 EOF
 
-cleanup
-
 }
 
 tmpfile="$(mktemp /tmp/cookies.sqlite.XXXXXXXXXX)"
-curlcookies="$(mktemp /tmp/curlcookies.XXXXXXXXXX)"
-echo $HOME/.mozilla/firefox/*.$profile/cookies.sqlite | { read cookie_file ;
-extract_cookies "$cookie_file" ;
-}
+cookie_file="$HOME/.mozilla/firefox/$profile/cookies.sqlite"
 
+if [ ! -f "$cookie_file" ]; then
+  die "No cookies.sqlite file found for profile '$profile'."
+fi
 
+extract_cookies "$cookie_file"
